[project]
name = 'Community-Urban-Planning-Platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.fund-allocation]
path = 'contracts/fund-allocation.clar'
clarity_version = 2
epoch = 2.5

[contracts.government-api-integration]
path = 'contracts/government-api-integration.clar'
clarity_version = 2
epoch = 2.5

[contracts.government-integration]
path = 'contracts/government-integration.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
